### ISSUE TITLE
creating a new VDOM and not passing options with IMAGES_SIZES property makes 💥

### ISSUE THREAD

**Issue by filmaj** [adobe/helix-pipeline#132]
This works fine (note the specific properties of the second argument passed into the VDOM constructor):

```
> VDOM=require('@adobe/helix-pipeline').utils.vdom
[Function: VDOMTransformer]
> transformer = new VDOM({
...   "type": "root",
...   "children": [{
.....     "type": "heading",
.....     "depth": 1,
.....     "children": [{
.......       "type": "text",
.......       "value": "Hello World"
.......     }]
.....   }]
... }, {IMAGES_SIZES:'100vw'})
VDOMTransformer {
  _matchers:
   [ [ [Function: match], [Function: handler] ],
     [ [Function: match], [Function: handler] ],
     [ [Function: match], [Function: handler] ] ],
  _root: { type: 'root', children: [ [Object] ] },
  _handlers:
   { root: [Function],
     paragraph: [Function],
     text: [Function],
     heading: [Function],
     thematicBreak: [Function],
     blockquote: [Function],
     list: [Function],
     listItem: [Function],
     table: [Function],
     tableRow: [Function],
     tableCell: [Function],
     html: [Function],
     code: [Function],
     yaml: [Function],
     definition: [Function],
     footnoteDefinition: [Function],
     emphasis: [Function],
     strong: [Function],
     delete: [Function],
     inlineCode: [Function],
     break: [Function],
     link: [Function],
     image: [Function],
     linkReference: [Function],
     imageReference: [Function],
     footnote: [Function],
     footnoteReference: [Function],
     embed: [Function] } }
```

If I omit this second argument, or don't pass in an object with an `IMAGES_SIZES` property, then things explode:

```
➜ node
> VDOM=require('@adobe/helix-pipeline').utils.vdom
[Function: VDOMTransformer]
> transformer = new VDOM({
...   "type": "root",
...   "children": [{
.....     "type": "heading",
.....     "depth": 1,
.....     "children": [{
.......       "type": "text",
.......       "value": "Hello World"
.......     }]
.....   }]
... })
TypeError: Cannot read property 'split' of undefined
    at image (/Users/maj/src/Adobe-Developer-Site/node_modules/@adobe/helix-pipeline/src/utils/image-handler.js:51:30)
    at new VDOMTransformer (/Users/maj/src/Adobe-Developer-Site/node_modules/@adobe/helix-pipeline/src/utils/mdast-to-vdom.js:64:25)
```

**Comment by filmaj** [comment]
I think the tests, even though on the surface they don't include this special property, use some kind of "coercing" utility to add this required parameter. But the docs in e.g. the README don't mention this - they probably should.

**Comment by trieloff** [comment]
Yes, we have the `coerce-defaults` function that is run as part of the pipeline construction. We might just want to run it again in the transformer if `options` is empty.

**Comment by filmaj** [comment]
OK, so the plan is leave the readme docs as is but add the coercing / default options inside the transformer?

I can send a PR for this, just want to make sure that sounds like the correct solution before I do that.

**Comment by trieloff** [comment]
Yes, I think that's the best way. Now since #135 is merged/fixed the coercer will be a bit more stable.

**Comment by trieloff** [comment]
@filmaj does this still need work?

**Comment by filmaj** [comment]
Yes, [the instructions in the README about how to construct a VDOM transformer](https://github.com/adobe/helix-pipeline#creating-responsive-images) cause things to explode for me:

```
19:38:14 in helix-pipeline on  master is 📦 v1.1.1 via ⬢ v10.9.0 took 6s
➜ node
> VDOM=require('./').utils.vdom;
[Function: VDOMTransformer]
> mdast={
... "type": "root",
... "children": [{
.....      "type": "heading",
.....      "depth": 1,
.....     "children": [{
.......       "type": "text",
.......      "value": "Hello World"
.......     }]
.....  }]
... };
{ type: 'root',
  children: [ { type: 'heading', depth: 1, children: [Array] } ] }
> widths=undefined;
undefined
> sizes=undefined;
undefined
> doc=new VDOM(mdast, {widths, sizes})
TypeError: Cannot read property 'split' of undefined
    at image (/Users/maj/src/helix-pipeline/src/utils/image-handler.js:47:30)
    at new VDOMTransformer (/Users/maj/src/helix-pipeline/src/utils/mdast-to-vdom.js:63:25)
> widths = {
...   from: 320,
...   to: 9600,
...   steps: 10
... };
{ from: 320, to: 9600, steps: 10 }
> doc=new VDOM(mdast, {widths, sizes})
TypeError: Cannot read property 'split' of undefined
    at image (/Users/maj/src/helix-pipeline/src/utils/image-handler.js:47:30)
    at new VDOMTransformer (/Users/maj/src/helix-pipeline/src/utils/mdast-to-vdom.js:63:25)
> sizes = [
...   '(min-width: 36em) 33.3vw',
...   '(min-width: 48em) calc(.333 * (100vw - 12em))',
...   '100vw'
... ]
[ '(min-width: 36em) 33.3vw',
  '(min-width: 48em) calc(.333 * (100vw - 12em))',
  '100vw' ]
> widths
{ from: 320, to: 9600, steps: 10 }
> sizes
[ '(min-width: 36em) 33.3vw',
  '(min-width: 48em) calc(.333 * (100vw - 12em))',
  '100vw' ]
> doc=new VDOM(mdast, {widths, sizes})
TypeError: Cannot read property 'split' of undefined
    at image (/Users/maj/src/helix-pipeline/src/utils/image-handler.js:47:30)
    at new VDOMTransformer (/Users/maj/src/helix-pipeline/src/utils/mdast-to-vdom.js:63:25)
> doc=new VDOM(mdast, {widths, sizes, IMAGES_SIZES:'100vw'})
VDOMTransformer {
  _matchers:
   [ [ [Function: match], [Function: handler] ],
     [ [Function: match], [Function: handler] ],
     [ [Function: match], [Function: handler] ] ],
  _root: { type: 'root', children: [ [Object] ] },
  _handlers:
   { root: [Function],
     paragraph: [Function],
     text: [Function],
     heading: [Function],
     thematicBreak: [Function],
     blockquote: [Function],
     list: [Function],
     listItem: [Function],
     table: [Function],
     tableRow: [Function],
     tableCell: [Function],
     html: [Function],
     code: [Function],
     yaml: [Function],
     definition: [Function],
     footnoteDefinition: [Function],
     emphasis: [Function],
     strong: [Function],
     delete: [Function],
     inlineCode: [Function],
     break: [Function],
     link: [Function],
     image: [Function],
     linkReference: [Function],
     imageReference: [Function],
     footnote: [Function],
     footnoteReference: [Function],
     embed: [Function] } }
```

So, at a minimum, you need to pass the `IMAGES_SIZES` parameter in the options. The readme says that the options object is optional - which it clearly is not.

**Comment by tripodsan** [comment]
image responsifier was removed. thus closing this issue.
