### ISSUE TITLE
random pipeline failures

### ISSUE THREAD

**Issue by stefan-guggisberg** [adobe/helix-pipeline#134]
We're experiencing random failures in pipeline processing during `hlx up`,  e.g.

```
[hlx] warn: tapping failed: TypeError: Cannot read property 'split' of undefined
```
```
TypeError: Cannot read property 'match' of undefined
    at Object.parse (/projects/helix-cli/node_modules/uri-js/dist/es5/uri.all.js:874:29)
    at uri (/projects/helix-cli/node_modules/@adobe/helix-pipeline/src/html/fetch-markdown.js:17:23)
    at fetch (/projects/helix-cli/node_modules/@adobe/helix-pipeline/src/html/fetch-markdown.js:78:10)
    at wrappedfunc (/projects/helix-cli/node_modules/@adobe/helix-pipeline/src/pipeline.js:158:18)
    at Promise.all.then (/projects/helix-cli/node_modules/@adobe/helix-pipeline/src/pipeline.js:287:37)
```

this is most likely a regression of #108 Refactor: set defaults

**Comment by stefan-guggisberg** [comment]
fixed via PR #135
