### ISSUE TITLE
Production Error: AJV can't find schema-draft-07

### ISSUE THREAD

**Issue by trieloff** [adobe/helix-pipeline#209]
This is a variant of the `{}` error. It happens only in production, and looking at the normal log files, you don't see enough, just:

```
2019-03-14T13:01:57.247Z       stdout: debug: Constructing HTML Pipeline
2019-03-14T13:01:57.247Z       stdout: debug: Creating pipeline
2019-03-14T13:01:57.248Z       stdout: debug: initializing ajv {"useDefaults":true,"coerceTypes":true}
2019-03-14T13:01:57.253Z       stdout: debug: error {"error":{},"request":"debug","activation":"b428bac388014bc1a8bac388019bc1b7","function":"html"}
```

As the error occurs during Pipeline construction, not pipeline creation, I've added some more debug output, only to discover this:

```
2019-03-14T13:06:18.478Z       stderr: Trace: Error: no schema with key or ref "http://json-schema.org/draft-07/schema#"
    at Ajv.validate (/nodejsAction/XXDnDjhB/node_modules/ajv/lib/ajv.js:95:19)
    at Ajv.validateSchema (/nodejsAction/XXDnDjhB/node_modules/ajv/lib/ajv.js:183:22)
    at Ajv._addSchema (/nodejsAction/XXDnDjhB/node_modules/ajv/lib/ajv.js:317:10)
    at Ajv.addSchema (/nodejsAction/XXDnDjhB/node_modules/ajv/lib/ajv.js:141:29)
    at schemaFiles.forEach (/nodejsAction/XXDnDjhB/node_modules/@adobe/helix-pipeline/src/utils/validator.js:45:17)
    at Array.forEach (<anonymous>)
    at ajv (/nodejsAction/XXDnDjhB/node_modules/@adobe/helix-pipeline/src/utils/validator.js:41:17)
    at coerce (/nodejsAction/XXDnDjhB/node_modules/@adobe/helix-pipeline/src/utils/coerce-secrets.js:15:25)
    at new Pipeline (/nodejsAction/XXDnDjhB/node_modules/@adobe/helix-pipeline/src/pipeline.js:85:5)
    at htmlpipe (/nodejsAction/XXDnDjhB/node_modules/@adobe/helix-pipeline/src/defaults/html.pipe.js:40:18)
    at htmlpipe (/nodejsAction/XXDnDjhB/node_modules/@adobe/helix-pipeline/src/defaults/html.pipe.js:68:13)
    at runner (/nodejsAction/XXDnDjhB/node_modules/@adobe/helix-pipeline/src/utils/openwhisk.js:134:12)
    at wrap (/nodejsAction/XXDnDjhB/node_modules/@adobe/openwhisk-loggly-wrapper/wrap.js:103:28)
    at Object.runPipeline (/nodejsAction/XXDnDjhB/node_modules/@adobe/helix-pipeline/src/utils/openwhisk.js:136:37)
    at NodeActionRunner.wrapped [as userScriptMain] (/nodejsAction/XXDnDjhB/html.js:129:28)
    at /nodejsAction/runner.js:100:45
    at new Promise (<anonymous>)
    at NodeActionRunner.run (/nodejsAction/runner.js:93:16)
    at doRun (/nodejsAction/src/service.js:256:31)
    at runCode (/nodejsAction/src/service.js:201:20)
```

**Comment by trieloff** [comment]
@filmaj that might be your bug.

**Comment by trieloff** [comment]
`$ unzip -p .hlx/build/html.zip node_modules/ajv/package.json` shows me that AJV 5.5.2 gets zipped instead of 6.10 which is needed by `helix-pipeline`

**Comment by trieloff** [comment]
The 5.5.2 version of `ajv` gets included by `har_validator`, which gets included by `request`, which we might exclude anyway, as it is container-provided.

**Comment by trieloff** [comment]
* `request` probably should not get excluded
* excluding `har-validator` will still pull the *wrong* `ajv` version

**Comment by filmaj** [comment]
Weird that pipeline requires 6.10 but 5.5.2 is included... wtf?

**Comment by trieloff** [comment]
WTF, thy name is webpack.

When you look at the `node_modules` directory, there is a `node_modules/request/node_modules` directory, containing `ajv` and `har-validator`. It looks like the `ajv` version gets pulled from there and webpack thinks it's good enough.

**Comment by filmaj** [comment]
I unzipped the `html` action and the only `ajv` I can find in the node modules dir is in the top level:

```
➜ find . -name ajv -type d
./ajv
```

**Comment by trieloff** [comment]
Take a look at the `package.json#version` for me it says: 5.5.2, so the `node_modules/request/node_modules/ajv` becomes `node_modules/ajv` in the ZIP file.

**Comment by filmaj** [comment]
Ah, ok.

So if I add `ajv: ^6.6.2` to the site's dependencies, run `hlx clean && hlx build && hlx deploy --dry-run`, then go in an unzip `.hlx/build/html.zip`, the `ajv` inside the node_modules inside the zip is still 5.5.2!

It looks to me like `hlx deploy` does some static analysis - so it doesn't matter what versions I specify in the package.json, `deploy` somehow decides which versions of which packages to bundle up?

**Comment by trieloff** [comment]
I've got a local fix, let's see if it improves the state of things in the runtime.

**Comment by trieloff** [comment]
It does!!! PR incoming.

**Comment by trieloff** [comment]
Closed in 
https://github.com/adobe/helix-cli/pull/645
