### ISSUE TITLE
[XSS] Sanitize generated markdown to avoid XSS attacks

### ISSUE THREAD

**Issue by asanso** [adobe/helix-pipeline#253]
The Links Markdown is easily escapable

either 

`[I'm an inline-style link](javascript://%0Dalert(document.domain))`

or

`[I'm an inline-style link](javascript:alert(document.domain))`

produces a valid XSS payload (after clicking on the produced link)

**Comment by asanso** [comment]
hlx --version

Warning: The current node version v11.9.0 does not satisfy 
the supported version range >=8.9 <9.0 || >=10.0 < 11.0.
You might encounter unexpected errors.   

0.14.4

**Comment by trieloff** [comment]
We should pipe the HTML through https://github.com/syntax-tree/hast-util-sanitize

**Comment by ramboz** [comment]
@asanso Feel free to review https://github.com/adobe/helix-pipeline/pull/263.
If you can think of some more tests to add, I'd be happy to update the PR.

**Comment by rofe** [comment]
I wonder why `htlengine` isn’t helping here... the same attack is prevented in Sling...

**Comment by tripodsan** [comment]
> I wonder why `htlengine` isn’t helping here... the same attack is prevented in Sling...

hmmm. the problem is probably that _they_ don't use the correct `@context` when outputting

**Comment by tripodsan** [comment]
I tried to reproduce the issue, but I only get an error:

```
[hlx] error: tapping failed: TypeError: Expected input to be a string
    at Function.picomatch.test (/Users/tripod/codez/helix/project-helix/modules/helix-cli/node_modules/picomatch/lib/picomatch.js:109:11)
    at matcher (/Users/tripod/codez/helix/project-helix/modules/helix-cli/node_modules/picomatch/lib/picomatch.js:57:48)
    at items.some.item (/Users/tripod/codez/helix/project-helix/modules/helix-cli/node_modules/@adobe/helix-pipeline/node_modules/micromatch/index.js:258:28)
    at Array.some (<anonymous>)
    at Function.micromatch.some (/Users/tripod/codez/helix/project-helix/modules/helix-cli/node_modules/@adobe/helix-pipeline/node_modules/micromatch/index.js:258:15)
    at embed (/Users/tripod/codez/helix/project-helix/modules/helix-cli/node_modules/@adobe/helix-pipeline/src/html/find-embeds.js:55:10)
    at map (/Users/tripod/codez/helix/project-helix/modules/helix-cli/node_modules/@adobe/helix-pipeline/src/html/find-embeds.js:73:7)
    at preorder (/Users/tripod/codez/helix/project-helix/modules/helix-cli/node_modules/unist-util-map/lib/unist-util-map.js:13:30)
    at bound (/Users/tripod/codez/helix/project-helix/modules/helix-cli/node_modules/unist-util-map/lib/unist-util-map.js:22:14)
    at Array.map (<anonymous>)
```

**Comment by tripodsan** [comment]
it works with references, though:

```
[I'm an inline-style link][xss0]

[I'm an inline-style link][xss1]

[xss0]: javascript:alert(document.domain)

[xss1]: javascript://%0Dalert(document.domain)
```

**Comment by tripodsan** [comment]
using `context = 'html'` removes all markup that contains links. see https://github.com/adobe/htl-spec/blob/master/SPECIFICATION.md#121-display-context

so with:

```
${content.document.body.innerHTML @ context='html'}
```

it becomes:

```
<p><img alt="helix-logo"> </p>

<p><a>I’m an inline-style link</a></p>
<p><a>I’m an inline-style link</a></p>
```

Unfortunately, also the `<img>` src is removed. @raducotescu is this expected?

**Comment by raducotescu** [comment]
Although it's not specified in the specification which tags / attributes should be left untouched when using the `html` context, the `<img>` tag is an attack vector. The `html` context's purpose is to sanitise user-generated HTML markup, which should have some limits - it must not be allowed to load content into the page.
