### ISSUE TITLE
context.request.headers is undefined on production

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pipeline#413]
seen on adobe dev site:

```
2019-07-16T00:48:36.918Z       stdout: error: Exception during #13/once:once from /nodejsAction/XXbdNKOd/html.js:257559:
TypeError: Cannot read property 'x-strain' of undefined
    at pre (/nodejsAction/XXbdNKOd/html.js:383905:56)
    at invoker (/nodejsAction/XXbdNKOd/html.js:383826:43)
    at once (/nodejsAction/XXbdNKOd/html.js:383850:14)
    at execFns (/nodejsAction/XXbdNKOd/html.js:109351:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2019-07-16T00:48:36.920Z       stdout: debug: context.error -> 500
```

probably from:
```
  logger.info(`strain header: ${context.request.headers['x-strain']}`);
```

/cc @ryanbetts

**Comment by tripodsan** [comment]
very unlikely, but this happens when action is invoked not via web-gateway.
