### ISSUE TITLE
Winston logger compatibility seems to be broken

### ISSUE THREAD

**Issue by Albinutte** [adobe/helix-pipeline#543]
It is no longer possible to run `helix_demo` project as described [here](https://www.project-helix.io/). I get these errors when running `hlx up`:
```
[hlx] error: Exception during #00/use:parseMarkdown from /Users/albina/Desktop/helix/hello_helix/.hlx/build/node_modules/@adobe/helix-pipeline/src/defaults/html.pipe.js:63:
RangeError: Maximum call stack size exceeded
    at DerivedLogger.(anonymous function) (/Users/albina/.nvm/versions/node/v10.16.3/lib/node_modules/@adobe/helix-cli/node_modules/winston/lib/winston/create-logger.js:95:19)
    at DerivedLogger.__ow_logger.log.msg [as log] (/Users/albina/Desktop/helix/hello_helix/.hlx/build/node_modules/@adobe/helix-pipeline/src/utils/openwhisk.js:133:60)
    at DerivedLogger.(anonymous function) (/Users/albina/.nvm/versions/node/v10.16.3/lib/node_modules/@adobe/helix-cli/node_modules/winston/lib/winston/create-logger.js:95:19)
    at DerivedLogger.__ow_logger.log.msg [as log] (/Users/albina/Desktop/helix/hello_helix/.hlx/build/node_modules/@adobe/helix-pipeline/src/utils/openwhisk.js:133:60)
    at DerivedLogger.(anonymous function) (/Users/albina/.nvm/versions/node/v10.16.3/lib/node_modules/@adobe/helix-cli/node_modules/winston/lib/winston/create-logger.js:95:19)
    at DerivedLogger.__ow_logger.log.msg [as log] (/Users/albina/Desktop/helix/hello_helix/.hlx/build/node_modules/@adobe/helix-pipeline/src/utils/openwhisk.js:133:60)
    at DerivedLogger.(anonymous function) (/Users/albina/.nvm/versions/node/v10.16.3/lib/node_modules/@adobe/helix-cli/node_modules/winston/lib/winston/create-logger.js:95:19)
    at DerivedLogger.__ow_logger.log.msg [as log] (/Users/albina/Desktop/helix/hello_helix/.hlx/build/node_modules/@adobe/helix-pipeline/src/utils/openwhisk.js:133:60)
    at DerivedLogger.(anonymous function) (/Users/albina/.nvm/versions/node/v10.16.3/lib/node_modules/@adobe/helix-cli/node_modules/winston/lib/winston/create-logger.js:95:19)
    at DerivedLogger.__ow_logger.log.msg [as log] (/Users/albina/Desktop/helix/hello_helix/.hlx/build/node_modules/@adobe/helix-pipeline/src/utils/openwhisk.js:133:60)
```

Looks like https://github.com/adobe/helix-pipeline/commit/4f3138171c95178b756a3cc072ebcf747da19069#diff-ebc7672f50d3fcf4ce1716569cc278bfL133-L138 is the reason for that.

**Comment by rofe** [comment]
Same as https://github.com/adobe/helix-cli/issues/1240, but keeping this open because the issue could indeed be pipeline related...

**Comment by kptdobe** [comment]
Interestingly, our smoke tests have been failing for 7 days because of this error... https://app.circleci.com/github/adobe/helix-continuous/pipelines

I wonder how we could have reached that state.
