### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by mcdrob** [adobe/helix-pipeline#545]
I'm getting the following error when I try to connect to the localhost. I get the same error running it through Powershell or WSL.
`    __ __    ___
   / // /__ / (_)_ __
  / _  / -_) / /\ \ /
 /_//_/\__/_/_//_\_\ v6.1.1

Building project files...
Using @adobe/helix-pipeline version 6.1.1 from .hlx\build\node_modules\@adobe\helix-pipeline.
html (src\html.htl)
Building project files...done 114ms
[hlx] info: Starting helix-simulator v2.17.5
[hlx] info: Local Helix Dev server up and running: http://localhost:3000/
[11520] HTTP: listening on port 51336
[hlx] error: Exception during #00/use:fetch from C:\code\hello_helix\.hlx\build\node_modules\@adobe\helix-pipeline\src\defaults\html.pipe.js:62:
RangeError: Maximum call stack size exceeded
    at DerivedLogger.(anonymous function) (C:\Users\[username]\AppData\Roaming\npm\node_modules\@adobe\helix-cli\node_modules\winston\lib\winston\create-logger.js:71:47)
    at DerivedLogger.__ow_logger.log.msg [as log] (C:\code\hello_helix\.hlx\build\node_modules\@adobe\helix-pipeline\src\utils\openwhisk.js:133:60)
    at DerivedLogger.(anonymous function) (C:\Users\[username]\AppData\Roaming\npm\node_modules\@adobe\helix-cli\node_modules\winston\lib\winston\create-logger.js:95:19)
    at DerivedLogger.__ow_logger.log.msg [as log] (C:\code\hello_helix\.hlx\build\node_modules\@adobe\helix-pipeline\src\utils\openwhisk.js:133:60)
    at DerivedLogger.(anonymous function) (C:\Users\[username]\AppData\Roaming\npm\node_modules\@adobe\helix-cli\node_modules\winston\lib\winston\create-logger.js:95:19)
    at DerivedLogger.__ow_logger.log.msg [as log] (C:\code\hello_helix\.hlx\build\node_modules\@adobe\helix-pipeline\src\utils\openwhisk.js:133:60)
    at DerivedLogger.(anonymous function) (C:\Users\[username]\AppData\Roaming\npm\node_modules\@adobe\helix-cli\node_modules\winston\lib\winston\create-logger.js:95:19)
    at DerivedLogger.__ow_logger.log.msg [as log] (C:\code\hello_helix\.hlx\build\node_modules\@adobe\helix-pipeline\src\utils\openwhisk.js:133:60)
    at DerivedLogger.(anonymous function) (C:\Users\[username]\AppData\Roaming\npm\node_modules\@adobe\helix-cli\node_modules\winston\lib\winston\create-logger.js:95:19)
    at DerivedLogger.__ow_logger.log.msg [as log] (C:\code\hello_helix\.hlx\build\node_modules\@adobe\helix-pipeline\src\utils\openwhisk.js:133:60)
[hlx] error: Unexpected error during pipeline execution:
RangeError: Maximum call stack size exceeded
    at DerivedLogger.(anonymous function) (C:\Users\[username]\AppData\Roaming\npm\node_modules\@adobe\helix-cli\node_modules\winston\lib\winston\create-logger.js:71:47)
    at DerivedLogger.__ow_logger.log.msg [as log] (C:\code\hello_helix\.hlx\build\node_modules\@adobe\helix-pipeline\src\utils\openwhisk.js:133:60)
    at DerivedLogger.(anonymous function) (C:\Users\[username]\AppData\Roaming\npm\node_modules\@adobe\helix-cli\node_modules\winston\lib\winston\create-logger.js:95:19)
    at DerivedLogger.__ow_logger.log.msg [as log] (C:\code\hello_helix\.hlx\build\node_modules\@adobe\helix-pipeline\src\utils\openwhisk.js:133:60)
    at DerivedLogger.(anonymous function) (C:\Users\[username]\AppData\Roaming\npm\node_modules\@adobe\helix-cli\node_modules\winston\lib\winston\create-logger.js:95:19)
    at DerivedLogger.__ow_logger.log.msg [as log] (C:\code\hello_helix\.hlx\build\node_modules\@adobe\helix-pipeline\src\utils\openwhisk.js:133:60)
    at DerivedLogger.(anonymous function) (C:\Users\[username]\AppData\Roaming\npm\node_modules\@adobe\helix-cli\node_modules\winston\lib\winston\create-logger.js:95:19)
    at DerivedLogger.__ow_logger.log.msg [as log] (C:\code\hello_helix\.hlx\build\node_modules\@adobe\helix-pipeline\src\utils\openwhisk.js:133:60)
    at DerivedLogger.(anonymous function) (C:\Users\[username]\AppData\Roaming\npm\node_modules\@adobe\helix-cli\node_modules\winston\lib\winston\create-logger.js:95:19)
    at DerivedLogger.__ow_logger.log.msg [as log] (C:\code\hello_helix\.hlx\build\node_modules\@adobe\helix-pipeline\src\utils\openwhisk.js:133:60)
RangeError: Maximum call stack size exceeded
    at DerivedLogger.__ow_logger.log.msg [as log] (C:\code\hello_helix\.hlx\build\node_modules\@adobe\helix-pipeline\src\utils\openwhisk.js:133:23)
    at DerivedLogger.(anonymous function) [as error] (C:\Users\[username]\AppData\Roaming\npm\node_modules\@adobe\helix-cli\node_modules\winston\lib\winston\create-logger.js:95:19)
    at DerivedLogger.__ow_logger.log.msg [as log] (C:\code\hello_helix\.hlx\build\node_modules\@adobe\helix-pipeline\src\utils\openwhisk.js:133:60)
    at DerivedLogger.(anonymous function) [as error] (C:\Users\[username]\AppData\Roaming\npm\node_modules\@adobe\helix-cli\node_modules\winston\lib\winston\create-logger.js:95:19)
    at DerivedLogger.__ow_logger.log.msg [as log] (C:\code\hello_helix\.hlx\build\node_modules\@adobe\helix-pipeline\src\utils\openwhisk.js:133:60)
    at DerivedLogger.(anonymous function) [as error] (C:\Users\[username]\AppData\Roaming\npm\node_modules\@adobe\helix-cli\node_modules\winston\lib\winston\create-logger.js:95:19)
    at DerivedLogger.__ow_logger.log.msg [as log] (C:\code\hello_helix\.hlx\build\node_modules\@adobe\helix-pipeline\src\utils\openwhisk.js:133:60)
    at DerivedLogger.(anonymous function) [as error] (C:\Users\[username]\AppData\Roaming\npm\node_modules\@adobe\helix-cli\node_modules\winston\lib\winston\create-logger.js:95:19)
    at DerivedLogger.__ow_logger.log.msg [as log] (C:\code\hello_helix\.hlx\build\node_modules\@adobe\helix-pipeline\src\utils\openwhisk.js:133:60)
    at DerivedLogger.(anonymous function) [as error] (C:\Users\[username]\AppData\Roaming\npm\node_modules\@adobe\helix-cli\node_modules\winston\lib\winston\create-logger.js:95:19)`

**Comment by MarquiseRosier** [comment]
Thanks for bringing this up mcdrob! We've already submitted a fix for the issue. You can read some details about the bug in https://github.com/adobe/helix-cli/issues/1240

and a PR has been submitted to fix it. This is at: 
https://github.com/adobe/helix-pipeline/pull/544

**Comment by rofe** [comment]
Duplicate of #543
