### ISSUE TITLE
fstab can't be loaded when pipeline used inside a deployed action

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pipeline#603]
```
2020-03-02T05:30:12.323Z       stderr: [ERROR] Exception during #01/use:fetchExternal from /nodejsAction/XXcBPldl/html.js:209481:
Error: /schemas/fstab.schema.json: ENOENT: no such file or directory, open '/schemas/fstab.schema.json'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at Object.readFileSync (/nodejsAction/XXcBPldl/html.js:46650:22)
    at MountConfig.init (/nodejsAction/XXcBPldl/html.js:47243:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

probably a packaging problem with webpack...

**Comment by tripodsan** [comment]
caused by https://github.com/adobe/helix-shared/issues/257
