### ISSUE TITLE
error when running `npm run lint`

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-pipeline#647]
**Description**
there are errors when running `npm run lint`:

```console
$ npm run lint

> @adobe/helix-pipeline@6.10.4 lint ./helix-pipeline
> npx eslint . && npm run types


> @adobe/helix-pipeline@6.10.4 types ./helix-pipeline
> npm run docs && node bin/schema2ts.js


> @adobe/helix-pipeline@6.10.4 docs ./helix-pipeline
> npx jsonschema2md -d src/schemas -o docs -x docs

loading 12 schemas
cannot resolve https://ns.adobe.com/helix/shared/markupconfig
writing schemas
writing schemas to ./helix-pipeline/docs
writing README
building readme
writing documentation
generating markdown
cannot resolve https://ns.adobe.com/helix/shared/markupconfig
cannot resolve https://ns.adobe.com/helix/shared/markupconfig
./helix-pipeline/docs/README.md created
(node:56117) UnhandledPromiseRejectionWarning: Error: Error downloading https://ns.adobe.com/helix/shared/markupconfig
getaddrinfo ENOTFOUND ns.adobe.com ns.adobe.com:443
    at ./helix-pipeline/node_modules/json-schema-ref-parser/lib/resolvers/http.js:126:16
    at process._tickCallback (internal/process/next_tick.js:68:7)

Error: getaddrinfo ENOTFOUND ns.adobe.com ns.adobe.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
(node:56117) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:56117) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by tripodsan** [comment]
@trieloff can you help?
