### ISSUE TITLE
Rendering a table with 5.7k rows times out

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pipeline#714]
Open https://hlxsite-kptdobe.hlx.page/test.html
The `test.md` behind:

```md
Hello World!

Welcome to my dummy website test!

---
https://adobe-my.sharepoint.com/personal/acapt_adobe_com/_layouts/15/guestaccess.aspx?share=EfdvdLr7abpNtTs96r9psKMBtVoQ4s5uLg12b9PJpRe-fA
1. {{import date}}: {{url}}
---
```

The Excel spreadsheet contains 5.7k rows but renders very quickly via helix-data-embed service: https://adobeioruntime.net/api/v1/web/helix/helix-services/data-embed@v1/https://adobe-my.sharepoint.com/personal/acapt_adobe_com/_layouts/15/guestaccess.aspx?share=EfdvdLr7abpNtTs96r9psKMBtVoQ4s5uLg12b9PJpRe-fA

I do not think this is helix-data-embed specific, I assume it is the full html rendering of such a large dom which takes too long. This may happen with a large md file too.

**Comment by kptdobe** [comment]
Locally, I get the following error (as a warning... ?): 

```
[hlx] warn: Error: Exception occurred while parsing yaml: YAMLException: end of the stream or a document separator is expected at line 2, column 19:
    1. {{import date}}: {{url}}
                      ^
https://adobe-my.sharepoint.com/personal/acapt_adobe_com/_layouts/15/guestaccess.aspx?share=EfdvdLr7abpNtTs96r9psKMBtVoQ4s5uLg12b9PJpRe-fA
1. {{import date}}: {{url}}
    at warn (.../hlxsite/.hlx/pages/master/node_modules/@adobe/helix-pipeline/src/html/remark-matter.js:36:17)
    at Of.frontmatter (.../hlxsite/.hlx/pages/master/node_modules/@adobe/helix-pipeline/src/html/remark-matter.js:99:14)
    at Of.tokenize [as tokenizeBlock] (.../hlxsite/.hlx/pages/master/node_modules/remark-parse/lib/tokenizer.js:62:18)
    at Of.parse (.../hlxsite/.hlx/pages/master/node_modules/remark-parse/lib/parse.js:33:20)
    at Function.parse (.../hlxsite/.hlx/pages/master/node_modules/unified/index.js:281:45)
    at parseMarkdown (.../hlxsite/.hlx/pages/master/node_modules/@adobe/helix-pipeline/src/html/parse-markdown.js:30:6)
    at execFns (.../hlxsite/.hlx/pages/master/node_modules/@adobe/helix-pipeline/src/pipeline.js:392:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by kptdobe** [comment]
Ok... this `warning` is a false positive: https://github.com/adobe/helix-pipeline/blob/master/src/html/remark-matter.js#L35-L42
If `data-embed` are supposed to be invalid frontmatter, then we should change that. I lost 2h analysing the code.

**Comment by tripodsan** [comment]
you should use empty lines eg:

```
---

https://adobe-my.sharepoint.com/personal/acapt_adobe_com/_layouts/15/guestaccess.aspx?share=EfdvdLr7abpNtTs96r9psKMBtVoQ4s5uLg12b9PJpRe-fA
1. {{import date}}: {{url}}

---
```

**Comment by kptdobe** [comment]
Same: 

```
[hlx] warn: Error: Found ambiguous frontmatter block: Block contains valid yaml, but it's data type is function String() { [native code] } instead of Object.Make sure your yaml blocks contain only key-value pairs at the root level!
https://adobe-my.sharepoint.com/personal/acapt_adobe_com/_layouts/15/guestaccess.aspx?share=EX0EOqFmkh9AtaHxid2nJ_kB2IleWLkGSx90s2NAB2t79w
1. {{import date}} - {{url}}
    at warn (/Users/acapt/work/dev/helix/playground/hlxsite/.hlx/pages/master/node_modules/@adobe/helix-pipeline/src/html/remark-matter.js:36:17)
    at Of.frontmatter (/Users/acapt/work/dev/helix/playground/hlxsite/.hlx/pages/master/node_modules/@adobe/helix-pipeline/src/html/remark-matter.js:104:14)
    at Of.tokenize [as tokenizeBlock] (/Users/acapt/work/dev/helix/playground/hlxsite/.hlx/pages/master/node_modules/remark-parse/lib/tokenizer.js:62:18)
    at Of.parse (/Users/acapt/work/dev/helix/playground/hlxsite/.hlx/pages/master/node_modules/remark-parse/lib/parse.js:33:20)
    at Function.parse (/Users/acapt/work/dev/helix/playground/hlxsite/.hlx/pages/master/node_modules/unified/index.js:281:45)
    at parseMarkdown (/Users/acapt/work/dev/helix/playground/hlxsite/.hlx/pages/master/node_modules/@adobe/helix-pipeline/src/html/parse-markdown.js:30:6)
    at execFns (/Users/acapt/work/dev/helix/playground/hlxsite/.hlx/pages/master/node_modules/@adobe/helix-pipeline/src/pipeline.js:392:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by kptdobe** [comment]
The frontmatter warning can be discussed here: https://github.com/adobe/helix-pipeline/issues/715

First real issue here is:

```
[hlx] error: Gateway timeout of 1000 milliseconds exceeded for https://adobeioruntime.net/api/v1/web/helix/helix-services/data-embed@v1/https://adobe-my.sharepoint.com/personal/acapt_adobe_com/_layouts/15/guestaccess.aspx?share=EfdvdLr7abpNtTs96r9psKMBtVoQ4s5uLg12b9PJpRe-fA
```

**Comment by kptdobe** [comment]
Then it is a performance issue in this area: https://github.com/adobe/helix-pipeline/blob/master/src/html/data-sections.js#L86-L107

**Comment by kptdobe** [comment]
Ok, found it. The `deepclone` copies the `meta.embedData` over and over: it clone 5.7k objects in 5.7k objects :)
