### ISSUE TITLE
data-embed format is considered as invalid frontmatter

### ISSUE THREAD

**Issue by kptdobe** [adobe/helix-pipeline#715]
Follow up of https://github.com/adobe/helix-pipeline/issues/714#issuecomment-627877564

In local dev and using data embed requires the markdown to look like:

```
Hello world

---
"https://docs.google.com/spreadsheets/d/e/2PACX-1vQ78BeYUV4gFee4bSxjN8u86aV853LGYZlwv1jAUMZFnPn5TnIZteDJwjGr2GNu--zgnpTY1E_KHXcF/pubhtml

Is foo {{foo}}?"
---

```

which is considered as invalid frontmatter by our `remark-matter` (see https://github.com/adobe/helix-pipeline/blob/master/src/html/remark-matter.js#L35-L42) and logged as a warning in dev. This is really confusing:

```
[hlx] warn: Error: Found ambiguous frontmatter block: Block contains valid yaml, but it's data type is function String() { [native code] } instead of Object.Make sure your yaml blocks contain only key-value pairs at the root level!
https://adobe-my.sharepoint.com/personal/acapt_adobe_com/_layouts/15/guestaccess.aspx
1. {{import date}} - {{url}}
    at warn (/Users/acapt/work/dev/helix/playground/hlxsite/.hlx/pages/master/node_modules/@adobe/helix-pipeline/src/html/remark-matter.js:36:17)
    at Of.frontmatter (/Users/acapt/work/dev/helix/playground/hlxsite/.hlx/pages/master/node_modules/@adobe/helix-pipeline/src/html/remark-matter.js:104:14)
    at Of.tokenize [as tokenizeBlock] (/Users/acapt/work/dev/helix/playground/hlxsite/.hlx/pages/master/node_modules/remark-parse/lib/tokenizer.js:62:18)
    at Of.parse (/Users/acapt/work/dev/helix/playground/hlxsite/.hlx/pages/master/node_modules/remark-parse/lib/parse.js:33:20)
    at Function.parse (/Users/acapt/work/dev/helix/playground/hlxsite/.hlx/pages/master/node_modules/unified/index.js:281:45)
    at parseMarkdown (/Users/acapt/work/dev/helix/playground/hlxsite/.hlx/pages/master/node_modules/@adobe/helix-pipeline/src/html/parse-markdown.js:30:6)
    at execFns (/Users/acapt/work/dev/helix/playground/hlxsite/.hlx/pages/master/node_modules/@adobe/helix-pipeline/src/pipeline.js:392:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

2 options:
1. remove the warning - debug might be enough
2. find another solution to describe data-embeds.

**Comment by tripodsan** [comment]
where are the `---` in your example? w/o those, it should not complain about frontmatter

**Comment by kptdobe** [comment]
sorry, I just fixed the sample.

**Comment by kptdobe** [comment]
The code is extracted from the tests: https://github.com/adobe/helix-pipeline/blob/master/test/fixtures/example-embeds.md

Tests trigger the warning.
